name: Build and release task
on:
  push:
    branches:
      - main
jobs:
  task1:
    runs-on: windows-latest
    env:
      APP_VERSION: 0.0.3
    steps:
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: actions/checkout@v2
      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: ${{ runner.os }}-QtCache
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          cached: ${{ steps.cache-qt.outputs.cache-hit }}
      - name: Test qmake
        run: where qmake
        shell: cmd
      - name: Install mugideploy
        run: python -m pip install mugideploy>0.0.7
        shell: cmd
      - name: Build app
        run: |
          qmake
          nmake release
          mugideploy collect --zip --bin release/decode-text.exe --app decode-text --version %APP_VERSION% --no-vcredist
        shell: cmd
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "decode-text-*-win64.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.APP_VERSION }}